import 'dart:ui';

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/foundation.dart';

enum AppStrings {
  appName,
  singerName,
  searchHint,
  navButtonHome,
  navButtonSearch,
  navButtonQueue,
  navButtonSettings,
  playlistsTitle,
  nowPlayingTitle,
  nowPlayingEmpty,
  timesPlayed,
  genericErrorMessage,
  artistsTitle,
  singersTitle,
  editSinger,
  cancel,
  save,
  name,
  emptyQueueMessage,
  noResults,
  songTitleHint,
  artistNameHint,
  searchTooShort,
  removeFromQueue,
  addYoutubeSong,
  youtubeSearchHint,
  youtubeSearchTitle,
  enterHost,
  connect,
  playButton,
  pauseButton,
  skipButton,
  volumeUp,
  volumeDown,
  updatePlaylists,
  invalidHost,
  youtubeSearchNotSupportedOnWeb,
  searchError,
  downloadApp,
  expectingSearch,
  noSingers,
  settingsTitle,
  ohNo,
  noPlaylistsFound,
  language,
  ;

  String get tr => key.tr();

  String get key => toString();
}

class AppTranslations {
  Map<Locale, Map<String, dynamic>> get keys => {
        const Locale('pt', 'BR'): {
          AppStrings.appName.key: 'FLUP Karaoke',
          AppStrings.singerName.key: 'Seu nome',
          AppStrings.searchHint.key: 'Insira o nome de uma música ou artista...',
          AppStrings.navButtonHome.key: 'Início',
          AppStrings.navButtonSearch.key: 'Buscar',
          AppStrings.navButtonQueue.key: 'Fila',
          AppStrings.navButtonSettings.key: 'Configurações',
          AppStrings.playlistsTitle.key: 'Playlists',
          AppStrings.nowPlayingTitle.key: 'Tocando agora',
          AppStrings.nowPlayingEmpty.key: 'Nenhuma música tocando agora',
          AppStrings.timesPlayed.key: 'tocada {} vezes',
          AppStrings.genericErrorMessage.key: 'Ocorreu um erro ):',
          AppStrings.artistsTitle.key: 'Artistas',
          AppStrings.singersTitle.key: 'Cantores',
          AppStrings.editSinger.key: 'Editar cantor',
          AppStrings.cancel.key: 'Cancelar',
          AppStrings.save.key: 'Salvar',
          AppStrings.name.key: 'Nome',
          AppStrings.emptyQueueMessage.key: 'Nenhuma música na fila',
          AppStrings.noResults.key: 'Nenhum resultado encontrado',
          AppStrings.songTitleHint.key: 'Título da música',
          AppStrings.artistNameHint.key: 'Nome do artista',
          AppStrings.searchTooShort.key: 'A busca deve ter pelo menos 3 caracteres',
          AppStrings.removeFromQueue.key: 'Remover da fila',
          AppStrings.addYoutubeSong.key: 'Adicionar música do Youtube',
          AppStrings.youtubeSearchHint.key: 'Insira o nome de uma música ou artista...',
          AppStrings.youtubeSearchTitle.key: 'Buscar no Youtube',
          AppStrings.enterHost.key: 'Insira o endereço do servidor',
          AppStrings.connect.key: 'Conectar',
          AppStrings.playButton.key: 'Tocar',
          AppStrings.pauseButton.key: 'Pausar',
          AppStrings.skipButton.key: 'Pular',
          AppStrings.volumeUp.key: '+ Volume',
          AppStrings.volumeDown.key: '- Volume',
          AppStrings.updatePlaylists.key: 'Atualizar playlists',
          AppStrings.invalidHost.key: 'Endereço inválido',
          AppStrings.youtubeSearchNotSupportedOnWeb.key: 'Busca no Youtube não é suportada no navegador.\nBaixe o aplicativo:',
          AppStrings.searchError.key: 'Ocorreu um erro ao buscar músicas',
          AppStrings.downloadApp.key: 'Baixar app',
          AppStrings.expectingSearch.key: 'Esperando busca',
          AppStrings.noSingers.key: 'Nenhum cantor cadastrado',
          AppStrings.settingsTitle.key: 'Configurações',
          AppStrings.ohNo.key: 'Oh não!',
          AppStrings.noPlaylistsFound.key: 'Nenhuma playlist encontrada',
          AppStrings.language.key: 'Idioma',
        },
        const Locale('en', 'US'): {
          AppStrings.appName.key: 'FLUP Karaoke',
          AppStrings.singerName.key: 'Your Name',
          AppStrings.searchHint.key: 'Enter a song or artist...',
          AppStrings.navButtonHome.key: 'Home',
          AppStrings.navButtonSearch.key: 'Search',
          AppStrings.navButtonQueue.key: 'Queue',
          AppStrings.navButtonSettings.key: 'Settings',
          AppStrings.playlistsTitle.key: 'Playlists',
          AppStrings.nowPlayingTitle.key: 'Now Playing',
          AppStrings.nowPlayingEmpty.key: 'No song playing now',
          AppStrings.timesPlayed.key: 'played {} times',
          AppStrings.genericErrorMessage.key: 'An error occurred ):',
          AppStrings.artistsTitle.key: 'Artists',
          AppStrings.singersTitle.key: 'Singers',
          AppStrings.editSinger.key: 'Edit singer',
          AppStrings.cancel.key: 'Cancel',
          AppStrings.save.key: 'Save',
          AppStrings.name.key: 'Name',
          AppStrings.emptyQueueMessage.key: 'No songs in queue',
          AppStrings.noResults.key: 'No results found',
          AppStrings.songTitleHint.key: 'Song title',
          AppStrings.artistNameHint.key: 'Artist name',
          AppStrings.searchTooShort.key: 'Search must be at least 3 characters long',
          AppStrings.removeFromQueue.key: 'Remove from queue',
          AppStrings.addYoutubeSong.key: 'Add song from Youtube',
          AppStrings.youtubeSearchHint.key: 'Enter a song or artist...',
          AppStrings.youtubeSearchTitle.key: 'Search on Youtube',
          AppStrings.enterHost.key: 'Enter server address',
          AppStrings.connect.key: 'Connect',
          AppStrings.playButton.key: 'Play',
          AppStrings.pauseButton.key: 'Pause',
          AppStrings.skipButton.key: 'Skip',
          AppStrings.volumeUp.key: '+ Volume',
          AppStrings.volumeDown.key: '- Volume',
          AppStrings.updatePlaylists.key: 'Update playlists',
          AppStrings.invalidHost.key: 'Invalid host',
          AppStrings.youtubeSearchNotSupportedOnWeb.key: 'Youtube search is not supported on web. Download the app:',
          AppStrings.searchError.key: 'An error occurred while searching for songs',
          AppStrings.downloadApp.key: 'Download App',
          AppStrings.expectingSearch.key: 'Expecting search',
          AppStrings.noSingers.key: 'No singers registered',
          AppStrings.settingsTitle.key: 'Settings',
          AppStrings.ohNo.key: 'Oh no!',
          AppStrings.noPlaylistsFound.key: 'No playlists found',
          AppStrings.language.key: 'Language',
        },
      };
}

class AppCustomLoader extends AssetLoader {
  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    EasyLocalization.logger.debug('Loading translations for locale: $locale');
    final translations = AppTranslations();
    final key = translations.keys[locale];
    return SynchronousFuture(key);
  }
}
